"use client";

import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'

import Header from './common/header/header'
import Footer from "./common/footer/footer";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Portfolio',
    description: 'Generated by Edwin Sidharta With Next.JS and Tailwind CSS',
}

export default function RootLayout({children}: { children: React.ReactNode })
{
    return (
        <html lang="en">
        <body className={inter.className}>
        <Header/>
        {children}
        <Footer/>
        </body>
        </html>
    )
}
